name: yaml-complete
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - gh
  - pip
  - ipykernel
  - pandas
  - openai
  - tqdm
  - pyyaml
  - transformers
  - pip:
    - github3.py