name: yaml-complete
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - accelerate
  - bitsandbytes
  - fire
  - gh
  - ipykernel
  - openai
  - pandas
  - pip
  - pytorch
  - pyyaml
  - tqdm
  - transformers
  - pip:
    - github3.py
    - vllm
    - https://github.com/casper-hansen/AutoAWQ/releases/download/v0.2.6/autoawq-0.2.6-cp39-cp39-linux_x86_64.whl