name: yaml-complete
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - accelerate
  - bitsandbytes
  - fire
  - gh
  - ipykernel
  - openai
  - pandas
  - pip
  - pytorch
  - pyyaml
  - tqdm
  - transformers
  - pip:
    - github3.py
    - vllm
    - flash_attn